spring:

  application:
    name: salles # le nom de notre application

  datasource:
    url: jdbc:h2:mem:salles
    username: root
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true # Pour eviter que le script data.sql s'execute avant l'initialisation Hibernate.
    h2:
      console.enabled: true
      settings.web-allow-others: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka #le lien vers le serveur eureka

server:
  servlet:
    context-path: /salles
